version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql/mysql-server:latest
    container_name: mysql-db2
    environment:
      - MYSQL_ROOT_PASSWORD=oldAgePass
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    restart: always

  #service 3: definition of your spring-boot app
  oldagemanagement:                        #it is just a name, which will be used only in this file.
    image: oldagemanagement                #name of the image after dockerfile executes
    container_name: oldagemanagement-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "8888:8888"                       #docker container port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/oldagemanagement?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: oldAgePass